### ISSUE TITLE
cf not working due wrong path!!!

### ISSUE THREAD

**Issue by saurabh021120** [xalanq/cf-tool#123]
panic: regexp: Compile(`C:\Users\saura\Desktop\IMP\CS PROGRAMS\Codeforces/contest/((?P<contestID>\d+)/((?P<problemID>\w+)/)?)?`): error parsing regexp: invalid escape sequence: `\U`

goroutine 1 [running]:
regexp.MustCompile(0xc0000400e0, 0x66, 0xc000107c38)
        /usr/local/go/src/regexp/regexp.go:311 +0x159
github.com/xalanq/cf-tool/cmd.parsePath(0xc00000b080, 0x27, 0x7bb84a)
        /Users/xalanq/go/src/github.com/xalanq/cf-tool/cmd/args.go:225 +0x2c7
github.com/xalanq/cf-tool/cmd.parseArgs(0xc000175bc0, 0x7375e0, 0xc000051ee0)
        /Users/xalanq/go/src/github.com/xalanq/cf-tool/cmd/args.go:93 +0x8f0
github.com/xalanq/cf-tool/cmd.Eval(0xc000175bc0, 0x1a, 0xc0001cc320)
        /Users/xalanq/go/src/github.com/xalanq/cf-tool/cmd/cmd.go:23 +0x7e
main.main()
        /Users/xalanq/go/src/github.com/xalanq/cf-tool/cf.go:160 +0x2d1
I am getting the following error message can you please help me?

**Comment by GoodCoder666** [comment]
I have the same problem.
[Here is it](https://github.com/xalanq/cf-tool/issues/124)

**Comment by Siddhant-K-code** [comment]
> C:\Users\saura\Desktop\IMP\CS PROGRAMS\Codeforces/contest/((?P<contestID>\d+)/((?P<problemID>\w+)/)?)?

Try Changing that path to :

`C:/Users/saura\Desktop/IMP/CS PROGRAMS/Codeforces/contest/((?P<contestID>\d+)/((?P<problemID>\w+)/)?)?`
