### ISSUE TITLE
cf tool panic

### ISSUE THREAD

**Issue by Witherrs** [xalanq/cf-tool#153]
panic: regexp: Compile(`F:\Codeforces/contest/((?P<contestID>\d+)/((?P<problemID>\w+)/)?)?`): error parsing regexp: invalid escape sequence: `\C`

goroutine 1 [running]:
regexp.MustCompile(0xc00008e9b0, 0x42, 0xc00007bc38)
        /usr/local/go/src/regexp/regexp.go:311 +0x159
github.com/xalanq/cf-tool/cmd.parsePath(0xc000086b60, 0x18, 0x7bb84a)
        /Users/xalanq/go/src/github.com/xalanq/cf-tool/cmd/args.go:225 +0x2c7
github.com/xalanq/cf-tool/cmd.parseArgs(0xc000173bc0, 0x7375e0, 0xc0000941a0)
        /Users/xalanq/go/src/github.com/xalanq/cf-tool/cmd/args.go:93 +0x8f0
github.com/xalanq/cf-tool/cmd.Eval(0xc000173bc0, 0x1b, 0xc0001cc240)
        /Users/xalanq/go/src/github.com/xalanq/cf-tool/cmd/cmd.go:23 +0x7e
main.main()
        /Users/xalanq/go/src/github.com/xalanq/cf-tool/cf.go:160 +0x2d1
I know that it is the problem of ":\" from the previous issues, but how/where can I change it to ":/"?

**Comment by Witherrs** [comment]
so where is the config file located? I am not able to find it  :(

**Comment by Witherrs** [comment]
oops I find the file ,it is located in the Users folder
