### ISSUE TITLE
submit的bug

### ISSUE THREAD

**Issue by xzz-233** [xalanq/cf-tool#6]
```
:~/codeforces/1161/f$ cf submit
There are multiple language match the file.
  0: GNU G++11 5.1.0
  1: GNU G++11 5.1.0
Please choose one(index): 
1
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/xalanq/cf-tool/cmd.getOneCode(0xc000075830, 0xc00000a5a0, 0x1, 0x4, 0x0, 0x1, 0xb, 0x15, 0x0)
	C:/project/go-project/src/github.com/xalanq/cf-tool/cmd/cmd.go:169 +0x58e
github.com/xalanq/cf-tool/cmd.Submit(0xc000075830, 0x0, 0x0)
	C:/project/go-project/src/github.com/xalanq/cf-tool/cmd/submit.go:27 +0x116
github.com/xalanq/cf-tool/cmd.Eval(0xc000075830, 0xc000075830, 0x7a0e85)
	C:/project/go-project/src/github.com/xalanq/cf-tool/cmd/cmd.go:24 +0x637
main.main()
	C:/project/go-project/src/github.com/xalanq/cf-tool/cf.go:122 +0x1e9
```

这里选0会正常提交，但是选1会报错

系统：ubuntu 18.04

**Comment by xalanq** [comment]
谔谔，你能把`~/.cfconfig`的文件内容发出来看看吗

以及`ls`一下当前的这个文件夹

**Comment by xzz-233** [comment]
```
{
  "username": "test12345",
  "password": "***",
  "template": [
    {
      "alias": "cpp",
      "lang": "42",
      "path": "/home/xzz/Templates/cpp.cpp",
      "suffix": [
        "cpp",
        "cpp"
      ],
      "before_script": "g++ -o $%file%$ $%full%$ -std=c++11 -DXZZSB -O0",
      "script": "$%file%$",
      "after_script": ""
    }
  ],
  "default": 0
}
```

**Comment by xzz-233** [comment]
当前文件夹里只有代码，可执行文件和样例。。

**Comment by xalanq** [comment]
你就ls一下，我看看有哪些文件

**Comment by xalanq** [comment]
以及你试试先将"suffix"里的多余"cpp"给删掉试试能不能提交。
如果是的话，我待会就把这个bug给修掉

**Comment by xalanq** [comment]
感觉和你目录下的文件没关系，应该你目录下就只有一个cpp文件。我似乎找到bug的地方了，有空我修下（应该很快）。

你把"cpp"去掉一个应该就能工作了的。

**Comment by xzz-233** [comment]
可以了emm
（出现两个cpp好像是配置的锅）
